language: go

sudo: required

go:
  - 1.14

go_import_path: github.com/root-gg/plik

before_install:
  # Update node_js version : https://github.com/travis-ci/travis-ci/issues/7108
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install stable
  - npm install -g bower

before_script:
  - go get -u golang.org/x/lint/golint

script:
  - make && make lint && make test && make test-backends && make docker